// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCoiUpnyGa5Onze8znh5fIq0x8ujRHyxk',
    appId: '1:522244731866:web:2820e3b3c154d1008606e3',
    messagingSenderId: '522244731866',
    projectId: 'chatapp-f3840',
    authDomain: 'chatapp-f3840.firebaseapp.com',
    storageBucket: 'chatapp-f3840.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvTM302kNVl3m86RwHzlfNgejenUyf07w',
    appId: '1:522244731866:android:d0ab19a062a866c58606e3',
    messagingSenderId: '522244731866',
    projectId: 'chatapp-f3840',
    storageBucket: 'chatapp-f3840.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs_HjoOQD848KAHD3GkQ15mJyhvf9j934',
    appId: '1:522244731866:ios:0259ddbed2c49fc98606e3',
    messagingSenderId: '522244731866',
    projectId: 'chatapp-f3840',
    storageBucket: 'chatapp-f3840.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs_HjoOQD848KAHD3GkQ15mJyhvf9j934',
    appId: '1:522244731866:ios:0259ddbed2c49fc98606e3',
    messagingSenderId: '522244731866',
    projectId: 'chatapp-f3840',
    storageBucket: 'chatapp-f3840.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCoiUpnyGa5Onze8znh5fIq0x8ujRHyxk',
    appId: '1:522244731866:web:226ca0cd9bc687e78606e3',
    messagingSenderId: '522244731866',
    projectId: 'chatapp-f3840',
    authDomain: 'chatapp-f3840.firebaseapp.com',
    storageBucket: 'chatapp-f3840.appspot.com',
  );
}
